server:
    port: 8084
eureka:
    client:
        service-url:
            defaultZone: http://discovery:8761/eureka/
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: acesso
                  uri: lb://acesso
                  predicates:
                  - Path=/estudante/**, /funcionario/**
                - id: livros
                  uri: lb://livros
                  predicates:
                    - Path=/livros/**
                - id: estoque
                  uri: lb://estoque
                  predicates:
                    - Path=/estoque/**