
version: "3"
services:
    acesso:
        build:
            context: ./acesso/demo/
        depends_on:
            - discovery
    livros:
        build:
            context: ./livros/demo/
        depends_on:
             - discovery
    estoque:
        build:
            context: ./estoque/demo
        depends_on:
             - discovery
    discovery:
        build:
            context: ./discovery/
        ports:
            - "8761:8761"
    gateway:
        build:
            context: ./gateway
        ports:
             - "8084:8084"